### ISSUE TITLE
[Feat] 지도를 서버 컴포넌트로 불러왔을 때의 문제점

### ISSUE THREAD

**Issue by ldcumg** [ldcumg/closure-closer#16]
## 서버 컴포넌트를 이용하려했던 이유
> 지도는 변하지 않고 유저와 상호작용하는 부분이 마커에 몰려있다고 생각하여 지도 부분은 서버, 마커 부분은 클라이언트 컴포넌트를 사용하려고 했습니다.

#### 1.  지도에서의 검색
> 지도에서의 검색 시 검색 위치로 지도를 이동하려면 쿼리 스트링을 이용하여 넘겨주는 방법 밖에 없어 검색마다 페이지 이동을 해야합니다.

#### 2. 지도 페이지, 전체 게시글 앨범 전환
<img width="548" alt="스크린샷 2024-10-23 오후 6 00 38" src="https://github.com/user-attachments/assets/925acc5e-c3be-4f00-bb0f-298236419e46"><br/>
> 조건부 렌더링을 사용하지 못 해 지도 페이지, 전체 게시글 앨범 전환 시마다 페이지 이동을 해야합니다.

**Comment by yuna-c** [comment]
[Create signed URLs](https://supabase.com/docs/reference/javascript/storage-from-remove)
+ 생소한 supabase 기능 
+ 실제 백엔드 + 프론트엔드에서 작업할시 aws s3 방식으로 작업하는데 Create signed URLs(supabase)기능과 다른점 

+ 스토리지에서 안전하게 접근하는법 (aws s3) -> 프리싸인드 유알엘 (백엔드 서버에서 스토리지에 접근할 수 있는 임시 유알엘을 제공하는데 수파베이스에서도 접근이 가능한지)-> 넥스트 환경에서 쓸수 있다면 좋을 것 같기도 하다

**Comment by yuna-c** [comment]
첫번째 블로그 주제
