### ISSUE TITLE
[Issue] 페이스북 로그인 개발자 사이트 본인 인증 이슈

### ISSUE THREAD

**Issue by jungminji0215** [ldcumg/closure-closer#19]
## 어떤 논의 사항인가요?

> 페이스북 로그인 작업 

페이스북 로그인 작업 중 개발자 사이트에 페이스북 아이디로 로그인하고 문자로 인증해야하는데
**문자가 안 오는 이슈** 발생

찾아보니 빈번하게 발생하는 문제인 것 같아요.  해결책을 찾아보았으나 잘 나오지 않았습니다.

## 이슈 상황

![스크린샷 2024-10-23 오후 10 01 01](https://github.com/user-attachments/assets/ccc82515-c858-41d2-a0b4-f3f1d7495bc8)

-> 여기 이후로 진행 불가

## 참고할만한 자료(선택)

- [수파베이스 페이스북 로그인 문서](https://supabase.com/docs/guides/auth/social-login/auth-facebook?queryGroups=environment&environment=client&queryGroups=framework&framework=nextjs)

- [페이스북 개발자 사이트](https://developers.facebook.com/)

## 방안

1. 인증 되는 분이 키 발급 받아주셔서 -> 정민지가 다시 진행
2. 페이스북 로그인 없애기

**Comment by escape-engineering** [comment]
저는 페북 아이디 해킹당해서 쉽지않네요

**Comment by jungminji0215** [comment]
논의 결과 일단 후순위로 결정
